const linkArray = {
  type: "array",
  items: { type: "string", pattern: "^([a-z0-9-]+:)?mx-[0-9a-f]{4,8}$" },
} as const;

export const recordSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "Mulch Expertise Record",
  description: "A single expertise record in a Mulch domain file",
  type: "object",
  definitions: {
    classification: {
      type: "string",
      enum: ["foundational", "tactical", "observational"],
    },
    evidence: {
      type: "object",
      properties: {
        commit: { type: "string" },
        date: { type: "string" },
        issue: { type: "string" },
        file: { type: "string" },
        bead: { type: "string" },
      },
      additionalProperties: false,
    },
    outcome: {
      type: "object",
      properties: {
        status: { type: "string", enum: ["success", "failure", "partial"] },
        duration: { type: "number" },
        test_results: { type: "string" },
        agent: { type: "string" },
        notes: { type: "string" },
        recorded_at: { type: "string" },
      },
      required: ["status"],
      additionalProperties: false,
    },
  },
  oneOf: [
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "convention" },
        content: { type: "string" },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
      },
      required: ["type", "content", "classification", "recorded_at"],
      additionalProperties: false,
    },
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "pattern" },
        name: { type: "string" },
        description: { type: "string" },
        files: { type: "array", items: { type: "string" } },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
      },
      required: [
        "type",
        "name",
        "description",
        "classification",
        "recorded_at",
      ],
      additionalProperties: false,
    },
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "failure" },
        description: { type: "string" },
        resolution: { type: "string" },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
      },
      required: [
        "type",
        "description",
        "resolution",
        "classification",
        "recorded_at",
      ],
      additionalProperties: false,
    },
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "decision" },
        title: { type: "string" },
        rationale: { type: "string" },
        date: { type: "string" },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
        context: { type: "string" },
        consequences: { type: "string" },
        decision_status: { type: "string" },
        related_files: { type: "array", items: { type: "string" } },
        related_mission: { type: "string" },
      },
      required: ["type", "title", "rationale", "classification", "recorded_at"],
      additionalProperties: false,
    },
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "reference" },
        name: { type: "string" },
        description: { type: "string" },
        files: { type: "array", items: { type: "string" } },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
      },
      required: [
        "type",
        "name",
        "description",
        "classification",
        "recorded_at",
      ],
      additionalProperties: false,
    },
    {
      type: "object",
      properties: {
        id: { type: "string", pattern: "^mx-[0-9a-f]{4,8}$" },
        type: { type: "string", const: "guide" },
        name: { type: "string" },
        description: { type: "string" },
        classification: { $ref: "#/definitions/classification" },
        recorded_at: { type: "string" },
        evidence: { $ref: "#/definitions/evidence" },
        tags: { type: "array", items: { type: "string" } },
        relates_to: linkArray,
        supersedes: linkArray,
        outcomes: { type: "array", items: { $ref: "#/definitions/outcome" } },
        audience: { type: "string" },
      },
      required: [
        "type",
        "name",
        "description",
        "classification",
        "recorded_at",
      ],
      additionalProperties: false,
    },
  ],
} as const;
